spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/party_bd
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: update
    show-sql: true

  liquibase:
    contexts: development  # Define los contextos específicos para el desarrollo
  sql:
    init:
      platform: postgresql
