spring:
  application:
    name: msParty
  liquibase:
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  profiles:
    active: development  # Activa el perfil por defecto (puedes sobrescribir con variables de entorno)
  jpa:
    hibernate:
      ddl-auto: update
com:
  weecover:
    msparty:
      thirdparty:
        url: http://example.com/api

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        BasicBinder: TRACE
        transaction: DEBUG